### ISSUE TITLE
Merge paths

### ISSUE THREAD

**Issue by jacoblapworth** [bodymovin/bodymovin#120]
Does this currently support merging paths from within After Effects?
I can't seem to get it to work, currently it fills the entire shape, no matter the merge path option – rather than cropping

**Comment by bodymovin** [comment]
Merge paths are not supported yet.
Sorry :/

**Comment by jesseylibby** [comment]
Any work arounds on this? I have a logo with a registered trademark that needs to reveal from behind a mask. I tried placing it in as an image file but the rendering of the png in Firefox looks butt ugly so I'd prefer to have it as a shape layer. Thoughts? :)

**Comment by bodymovin** [comment]
I don't know how the logo looks like. But can't you reproduce it with masks?

**Comment by jesseylibby** [comment]
That's what I thought but inverted masks aren't supported, right? I'm sure there's a solution I'm not seeing. Below is a screenshot of the mask option. I can't show you the whole thing due to privacy reasons but hopefully this gets the idea across.

![screen shot 2016-07-26 at 12 55 31 pm](https://cloud.githubusercontent.com/assets/20570973/17149315/5a86fc84-5330-11e6-9623-9da3dda3f7c1.png)

**Comment by jesseylibby** [comment]
Guess I'm a little blonde. The issue was that all the mask paths were set to difference. They needed to be add and subtract.

:)
