### ISSUE TITLE
Is it possible to decrease file?

### ISSUE THREAD

**Issue by ArkRide** [bodymovin/bodymovin#144]
Hey,
First of all thanks for your plug in, it's amazing, I have been using it for a year already so far.
Now I encoutered an issue where I need to upload animations to web, and they should not be bigger than 60kb or so. The pictures i use inside the project weigh very little themselves (10-20kb) while the whole html file weighs around 220kb. I only add a couple of animations there, like positional changes. Is it possible to decrease the size of the html at least to some extent?
Would appreciate your help!

**Comment by bodymovin** [comment]
Hi, the images exported from AE are pngs and are not well compressed.
You can replace them with your original versions in the images folder or maybe user a service like "tinypng" to have them compressed.
If you can use vectors instead of rasterized images, it will be even lighter.

Also, you should gzip the exported json as well as the js player when uploading them to a server. The filesize of those files can decrease 5 times or more.

Let me know if that helps.
