### ISSUE TITLE
When using .ai file type for img causes unwanted outer rasterized line

### ISSUE THREAD

**Issue by JackMoGraphics** [bodymovin/bodymovin#158]
Hi Hernan,

I'm having trouble rendering a logo.

I am using two .ai files to make up two parts of the logo, they have a gradient on them from AI. This renders fine. However, i get an unwanted thin grey/brown line that isn't in the image originally but the render rasterises the edges making it look scruffy.

I would normally convert them to shapes but because i want a gradient i can't.
I'll show a small screenshot example here:

<img width="266" alt="screen shot 2016-10-14 at 10 04 31" src="https://cloud.githubusercontent.com/assets/19855318/19381898/a70c771a-91f5-11e6-8f59-af7d5965e7a6.png">

I can not share the AE file however due to the nature of the project.

It should be a solid white Logo with no outer lines. Any suggestions? 

Thanks as always.

**Comment by bodymovin** [comment]
Hi, when exporting images, bodymovin relies on the AE method saveFrameToPng that sometimes doesn't handle well transparency.
Can you replace the images exported from AE with your own images saving them directly from AI?

Another option, since the player supports gradients, is to reproduce the gradients over the shapes in AE and they will be exported as vectors.

**Comment by JackMoGraphics** [comment]
Thanks for the speedy reply as always.

Will give this a go and let you know how it goes. 


Cheers!

**Comment by bodymovin** [comment]
sure, let me know if I can help you further.

**Comment by JackMoGraphics** [comment]
Yup all works good now!  CC wasn't updating the plugin and had to manually uninstall and reinstall to get the gradient support update. 

Also managed to work around the AI issue doing as you instructed. 


Cheers thank you!
