### ISSUE TITLE
WebGL & Canvas2D

### ISSUE THREAD

**Issue by mattdesl** [bodymovin/bodymovin#18]
It might be nice to build some docs around the JSON output format so that developers could start to build other renderers. In many cases Canvas2D/WebGL will out-perform SVG.

**Comment by bodymovin** [comment]
@mattdesl I will as soon as I add expressions.  
They will change the json format and won't be compatible with the current one.  
Regarding a canvas renderer, the plugin has one. But svg filters outperform canvas pixel manipulation.  
I don't know if it's easy to implement similar svg filters in Webgl. I'll look into this. Any suggestions where to start?

**Comment by mattdesl** [comment]
What kind of filters do designers typically go for? I imagine a WebGL/Canvas2D renderer might be more limited, i.e. only implementing certain features, and maybe no support for filters at all, but providing greater performance for certain scenes.

**Comment by bodymovin** [comment]
@mattdesl I think AE alpha/luma track mattes are a must. I need to get a layer to work as a mask for another one.
next on the list would probably be blur effects, and some layer styles like strokes.

**Comment by Tolmark12** [comment]
Is the canvas demo in the readme accurate? I've tried that code snippet, but it appears that the library is still generating a svg.

**Comment by bodymovin** [comment]
@Tolmark12  Have you changed the animType to 'canvas'?

**Comment by Tolmark12** [comment]
@bodymovin No sir I did not :facepalm: Working great now, sheesh!

**Comment by boulabiar** [comment]
Hi,

If you can export to svg, it can be self contained and added to more
content in a web page.
Any idea how to do the same in webgl?
Imagine I have a bigger scene, how to add the animation exported feom
bodymovin as an element in that scene?

Thanks

**Comment by bodymovin** [comment]
@boulabiar There's also the canvas renderer. I guess you could render on a canvas outside the dom and then draw the result on the webgl.
But ideally, a webgl renderer would be the best option, where you could add the animation as a geometry or texture.
Right now, a webgl renderer is not on my pipeline. I explored some time ago integrating with three.js and was promising.

**Comment by dionysiusmarquis** [comment]
Rendering svg exclusively in GL context isn't trivial. You need to tesselate every vector -shape, -line… etc. See  [nanovg](https://github.com/memononen/nanovg), [libtess2](https://github.com/memononen/libtess2). Tesselating in js will be very slow. Complex 2d vector graphics isn't really what GL is meant for.

**Comment by DrSensor** [comment]
Good news! Skia has a [canvaskit](https://skia.org/user/modules/canvaskit) package which can be used to play Lottie JSON in WebGL canvas

https://github.com/google/skia/blob/312535b47d389e55a6666ea82638458245a421e0/modules/canvaskit/canvaskit/types/index.d.ts#L327-L336

**Comment by sb2702** [comment]
I know I'm a bit late to the party, but last year I built an SVG renderer in WebGL to tackle the high CPU usage of rendering SVG animations.

@dionysiusmarquis is mostly right- rendering SVG exclusively in a GL context isn't trivial, and tesselating every vector shape would be computationally expensive.

Where we made a breakthrough was - **you don't need to tesselate vector shape**. I wrote a quick document explaining [how you can render SVG without tesselation)(https://files.vectorly.io/webgl-svg-renderer/index.html)

We stopped working on this last year because startup startup stuff, but occurred to me that the same idea could be useful to implement as a WebGL engine for Lottie animations, in cases where CPU usage needs to be reduced.

If there's interest in picking this up as a project, I'd be happy to open source what we have, though we didn't build a FULL svg renderer, so it may require a lot more work to actually be production ready.


**Example**

SVG Animation (~20% CPU Usage): https://files.vectorly.io/demo/sidebyside-v1/index.html   
WebGL Animation (~1% CPU Usage): https://files.vectorly.io/demo/v0-2-simpsons-250kbps/index.html

You can profile the CPU Usage in Chrome

**Why we built it:**
Long story: https://files.vectorly.io/Vectorization+Whitepaper+v06.20.pdf

**Comment by shaafiee** [comment]
https://github.com/LottieFiles/glottie

**Comment by sb2702** [comment]
@shaafiee  - Ah, okay, well I'm glad there's already an existing project!

**Comment by boulabiar** [comment]
> If there's interest in picking this up as a project, I'd be happy to open source what we have, though we didn't build a FULL svg renderer, so it may require a lot more work to actually be production ready.


If there is still a possibility to open source a basic example it can be very nice for future references and comparisons.

**Comment by denghongcai** [comment]
@sb2702 It's 2025 now, and your examples are no longer accessible. Could you share an open-source example for learning purposes?

**Comment by sb2702** [comment]
I apologize for the delay on this. 

Here is the source code:
https://github.com/Vectorly/webgl-player

**The complex reason I never shared the source and why the demos aren't available**
I built that code while working on a startup called Vectorly. My company was acquired in December 2021 by a company called Hopin. They acquired most of the IP, including the domain names of vectorly.io. The acquiring company, Hopin, itself was acquired by a Private Equity firm in 2024, which inherited the IP (including the domain names). The IP and domain names are now owned by a random Private Equity firm, and they fired me and everyone else, so that's why the demos are no longer accessible and I can't do anything about it. 

In 2020, a patent troll tried to sue me for building a vector-graphics based video codec, claiming I infringed on their overly broad patent related to "media processing". Because of this, Hopin (which acquired my company) specifically carved out the IP related to vector-graphics-based encoding and rendering, because they didn't want to take on that liability, so I technically personally "own" that IP. They also specifically also told me not to talk about it though to avoid attracting attention, which is why I didn't share source code even though I owned it. I complied because, well, Hopin was my employer from 2021 to 2024.

Hopin no longer exists as a company, and so who cares? I also had to consult with a lawyer to double check it was fine to share this stuff without being sued.

Sorry for all this stupid commercial / legal bs, this should have just been a simple open source project from the beginning.
