### ISSUE TITLE
XMLHttpRequest

### ISSUE THREAD

**Issue by mrsamse** [bodymovin/bodymovin#199]
Hi there

I want to use bodymovin for a banner ad. It works fine but the problem is, that they (the company which displays the ad on their website) needs to test the ad on a local machine. When I use bodymovin on a local machine, I get this error message: 

`bodymovin.js:formatted:5556XMLHttpRequest cannot load file:///Volumes/TS_Kundenprojekte/1-AKTIVE-KUNDEN/homegate/004-onlinehypoth…lercoaster/gwd_preview_banner_rollercoaster_994x250_de/assets/rechner.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.AnimationItem.setParams @ bodymovin.js:formatted:5556s @ bodymovin.js:formatted:5377c @ bodymovin.js:formatted:5907(anonymous function) @ index.html:373`

How can I run bodymovin on a localmachine?

**Comment by bodymovin** [comment]
Browsers don't allow loading json files when executing html from the filesystem.
You can use the "standalone" option in the AE settings in the bodymovin panel that exports a single .js file with the player and the animation merged.

Or, you can create a new .js file with a single variable containing all the json information and load it as a separate script tag. In the loadAnimation data, instead of passing a path to get the json, you'll have to pass the variable you created.

the data.js should look like this:
var animationData={[HERE-GOES-ALL-THE_JSON-INFO]}

and the index.html should look something like this:
var animParams = {
        container: document.getElementById('bodymovin'),
        renderer: 'svg',
        loop: true,
        autoplay: true,
        animationData: animationData
};

If you need more help, I can send you an example with your files.
