### ISSUE TITLE
Animation doesn't work well in IE / Edge

### ISSUE THREAD

**Issue by mingjuitsai** [bodymovin/bodymovin#204]
Hi, 

Love the plugin, but somehow this animation that we did, doesn't work well on IE / Edge :( 
The linked letter images look broken, otherwise looking awesome in all other modern browsers!

Just wondering if you could take a look at the demo.html and perhaps give me some pointers..? Thank you so much.

[animation.zip](https://github.com/bodymovin/bodymovin/files/653741/animation.zip)

**Comment by bodymovin** [comment]
I guess you're using some kind of stroke as mask, is that right?
can you share the .ae file so I can take a look?
by the way, it's best if you convert your letters to shapes, so they get exported as vectors and don't break when resized

**Comment by daveWatermark** [comment]
Hi There!

I'm the animator working on this piece with the OP - I've attached the collected project for you to have a look at.

Have tried to keep the setup simple: all the letters & numbers have been converted to shapes in AI (no live text in AE) and the masking has been created with generic masks or alpha track mattes.

Any advice you could give would be greatly appreciated.

[animation_collection.zip](https://github.com/bodymovin/bodymovin/files/659677/animation_collection.zip)

**Comment by bodymovin** [comment]
The missing lines in Edge are related to using alpha masks that have only strokes and not fills on them. Edge doesn't handle that case correctly. If you can correct those masks and use fills it should be fine.
By the way, you should convert those .ai layers to shapes in AE because they'll get exported as vectors and not rasterized pngs (right click on each ai layer and select Create Shapes from Vector Layer). The problem in your case is that since you already added masks, you'll need to adjust them again because AE messes masks up when converting to shapes.

**Comment by mingjuitsai** [comment]
Hi,

We were able to solve the issue by re-animating it! 
Thanks very much for your help. Here's our final file if anyone's interested 
[anim_update.zip](https://github.com/bodymovin/bodymovin/files/662898/anim_update.zip)
