### ISSUE TITLE
Trim pathing error

### ISSUE THREAD

**Issue by TomHoenderdos** [bodymovin/bodymovin#222]
Hi Hernan!

Unfortunately another trim path issue :( Maybe even multiple!
Attached is the zip with including the bodymovin export ;)
Hopefully its fixable

[Trim paths - animatie .zip](https://github.com/bodymovin/bodymovin/files/716594/Trim.paths.-.animatie.zip)

**Comment by Jeremy-Knudsen** [comment]
Hi Tom, I took a look at your test project (just out of curiosity) and I get an error--and it may be just me, but I thought I'd share it anyway if it could be of some help:

> SCRIPT5007: Unable to get property 'effect' of undefined or null reference
> eval code (8) (2,1)

When I inspect the eval code, I see this, with the error indicator pointing to line 2:

`var fn = function(){var $bm_rt;
$bm_rt = comp('Kleuren').layer('Hoofdkleur').effect('Fill')('ADBE Fill-0002');;this.v = $bm_rt;}`

**Comment by TomHoenderdos** [comment]
Hi jeremy!

We have used an expression so you have to include an extra comp with
bodymovin, you can click on the cog wheel to enable extra comps and select
the 'kleuren' comp. ( forgot to translate the comps, sorry!)

Op do 19 jan. 2017 18:56 schreef Jeremy Knudsen <notifications@github.com>:

**Comment by bodymovin** [comment]
I think this time it's not a trim path issue, but an effect issue.  
Because of the way that browsers handle filters (that is used in this case to apply the fill effect of AE), strokes are not correctly measured and they end up cropped.
If you add a transparent rectangle as part of each layer with strokes that cover the whole surface the stroke animates, browsers use the rectangle as measurement and strokes with effects don't get cropped.
I'm attaching the project as an example. Check the comp "Order_her".
[Animatie 3.zip](https://github.com/bodymovin/bodymovin/files/718002/Animatie.3.zip)

**Comment by Jeremy-Knudsen** [comment]
Any chance the workaround of adding a transparent rectangle could be done automatically by the Bodymovin extension when rendered?

**Comment by bodymovin** [comment]
Good idea :)
I'll think about it.
