### ISSUE TITLE
Fill swapping to background

### ISSUE THREAD

**Issue by anthonysapp** [bodymovin/bodymovin#224]
Wondering if you can point me in the right direction on an issue I'm having. I am bringing in assets from Illustrator, and following your instructions, but sometimes my fills are getting "reversed" so that the fill I use is becoming a background colour for the object.

I've attached a screenshot and an .aep file if you require. I'm sure it's something small I'm missing. Thanks for the great plugin / workflow!

![issue_screenshot](https://cloud.githubusercontent.com/assets/5347604/22126073/287585fc-de64-11e6-927a-ce3334db62c1.png)
[fill_to_background_issue.zip](https://github.com/bodymovin/bodymovin/files/717822/fill_to_background_issue.zip)

**Comment by bodymovin** [comment]
This is related to converting AI layers to shapes.
In some cases AE adds an extra square path and merges it with the original shape.  
Since merge paths are not yet supported, they are exported incorrectly.
If you go to your "body" layer and erase in the Contents "Path 2" and "Merge Paths 1", it should export fine.

**Comment by anthonysapp** [comment]
Thanks! Will give this a go this morning! Much appreciated.

**Comment by anthonysapp** [comment]
Worked, thanks so much for the reply. Closing issue :)
