### ISSUE TITLE
Loading multiple animation files with one player

### ISSUE THREAD

**Issue by phantomboogie** [bodymovin/bodymovin#288]
Is it possible to write a single player to load multiple animation files rather than for each animation file. Is it possible to use one player to play multiple animations?
Here's my current code. 

```
 var bmAnim = document.querySelector('#animation');
        
    var animData1 = {
            container: sun,
            name: 'privacy',
            renderer: 'svg',
            loop: false,
            autoplay: false,
            path: '_animation/sun.json',
    };
    
    var animData2 = {
            container: payment,
            name: 'payment',
            renderer: 'svg',
            loop: false,
            autoplay: false,
            path: '_animation/moon.json',
    };
    
    var animData3 = {
            container: passcode,
            name: 'passcode',
            renderer: 'svg',
            loop: false,
            autoplay: false,
            path: '_animation/stars.json',
    };
    
var anim = bodymovin.loadAnimation(animData1, animData2, animData3);

```

What I'm thinking is something like 

```
 var bmAnim = document.querySelector('#animation');

    var animData1 = {
            container: passcode, 
            renderer: 'svg',
            loop: false,
            autoplay: false,
            path: '_animation/sun.json',
            path: '_animation/moon.json',
            path: '_animation/stars.json',
    };

var anim = bodymovin.loadAnimation(animData1);
```

Thanks

**Comment by bodymovin** [comment]
if you load all three animations in a single html element (passcode), they would all overlap between each other.
Do you want a single player in order to control them all at once or have them all synced between each other for example?

**Comment by phantomboogie** [comment]
I was trying to get them all synced to each other on hover which I figured out.

I was more trying to figure out if there was a shorter way of writing the bodymovin.loadAnimation()  code since if I had 10 animations on a page, I'd have to write loadAnimation 10 times which takes up quite a bit of space. 

I'm also trying to get each animation to be next to each other but for some reason, no matter how much I set the width or display properties, they are all sitting on top of each other. Any ideas?

**Comment by bodymovin** [comment]
have you tried using display: inline-block to the containing div?
regarding code repetition, you can add a function that loads the animation and only pass the needed params to it.

**Comment by phantomboogie** [comment]
Yup. Got the positioning figured out. Thanks.

Back to the multiple animations issue, all my animations are in one js file and I'm now calling them through an array. 

I want to pause each array element individually but instead, every animation I click is only playing the last item in the array. I know I can probably write individual functions with eventlisteners for each array item, but is there a way to do it globally? 

Here's the code snippet.

    var elementsArr = ['map', 'privacy', 'payment', 'rewards', 'cat', 'passcode'];
    var element;

    function buildIllus(){
        for(var i=0;i<illustArr.length;i+=1){
            illust = document.getElementById(illustArr[i]);
            var params = {
                container: illust,
                name: 'passcode',
                autoplay: false,
                loop: false,
                animationData: animations[illustArr[i]],
                renderer: 'svg'
            };
            
            var anim = bodymovin.loadAnimation(params);
             
            illustArr.forEach(function (e) {
                document.getElementById(e).addEventListener('click', function() {
            anim.goToAndPlay(0, true)
            }, false);}
            )
        }
    };

**Comment by bodymovin** [comment]
this is related to Javascript scoping. When you declare all the click functions inside your loop, that function gets scoped with your variable declaration. So once the event is dispatched, the anim value is always the last value of the loop.
You need to create a separate scope for each function invoked in the loop in order to get the anim variable scoped correctly.
I didn't test it, but something like:
```javascript
var elementsArr = ['map', 'privacy', 'payment', 'rewards', 'cat', 'passcode'];
var element;

function addListenerToElement(e, anim){
  document.getElementById(e).addEventListener('click', function() {
    anim.goToAndPlay(0, true)
  }, false)
}

function buildIllus(){
    for(var i=0;i<illustArr.length;i+=1){
        illust = document.getElementById(illustArr[i]);
        var params = {
            container: illust,
            name: 'passcode',
            autoplay: false,
            loop: false,
            animationData: animations[illustArr[i]],
            renderer: 'svg'
        };
        
        var anim = bodymovin.loadAnimation(params);
         
        illustArr.forEach(function (e) {
          addListenerToElement(e, anim)
          })
    }
};
```

**Comment by motionvideosuk** [comment]
Could someone help me out with a similar issue please. I'm trying to get these 3 stars to play next to each other. 

<img width="642" alt="Screenshot 2019-03-30 at 10 06 28" src="https://user-images.githubusercontent.com/49041491/55274724-85549200-52d3-11e9-813e-d5ac32ce8705.png">

My code is in columns in the backend of Wordpress which I can add custom CSS elements to but for the life of me I just can't get them to float next to each other instead of under each other.

<img width="1703" alt="Screenshot 2019-03-30 at 10 07 47" src="https://user-images.githubusercontent.com/49041491/55274736-b208a980-52d3-11e9-8fa3-040749f993a9.png">

My test page is this:
https://motionvideos.uk/bodymovin-test/

My code is this:

`<div style="width:100%;height:100%;" id="bodymovin"></div>

<script>
    var animData = {
        wrapper: document.getElementById('bodymovin'),
        animType: 'svg',
        loop: true,
        autoplay: true,
        path: '/bodymovin/test-red.json'

    };
    var anim = bodymovin.loadAnimation(animData);
    bodymovin.setSubframeRendering(true);
</script>`

Hope someone can help.

Thanks in advance.
