### ISSUE TITLE
Extension source

### ISSUE THREAD

**Issue by sbalko** [bodymovin/bodymovin#362]
Do you plan to make the extension source files available? Currently, they are webpacked into a single main.js file, which makes it difficult to contribute/extend the AE extension as such.

**Comment by bodymovin** [comment]
if you mean the AE extension, it's on another repository
https://github.com/bodymovin/bodymovin-extension

**Comment by bigxixi** [comment]
how to use the extension source?
after I make some change to the files, should I pack them into zxp file and reinstall?

**Comment by bodymovin** [comment]
you can run "npm run build" in the console to build the files.
Then in windows I sign it like this:
ZXPSignCmd.exe -sign "[Path to file]" .\bodymovin.zxp cert.p12 password -tsa https://timestamp.geotrust.com/tsa

**Comment by bigxixi** [comment]
Thank you!

**Comment by bassemgithub** [comment]
why can't use bodymovin builded by me into adobe after effect ?

**Comment by bodymovin** [comment]
@bassemgithub Hi, can you specify what is happening?

**Comment by bassemgithub** [comment]
i had success to create the bodymovin.zxp 
using this command 
 - "npm run build" 
 - "ZXPSignCmd.exe -sign "[Path to file]" .\bodymovin.zxp cert.p12 password" here without -tsa https://timestamp.geotrust.com/tsa because it give me error but i read that isn't mandatory.  
 after i get my bodymovin.zxp i tryied to install it into after effect using zxp installer but it fail in spite of it i can install the bodymovin.zxp created here  https://github.com/airbnb/lottie-web/tree/master/build/extension

Note: i trying to rebuild the bodymoin because i would like to add new functionality

**Comment by bodymovin** [comment]
@bassemgithub where does it fail? Are you getting any specific error?

**Comment by bassemgithub** [comment]
it fail when i try to install it into adobe after effect 
i  get this error "custom installation failed: could not read zxp data" 
if you like i can send to u the created file.zxp ?

**Comment by bodymovin** [comment]
@bassemgithub yes, please

**Comment by bassemgithub** [comment]
the file is big so can't send it in attachment if you give me the mail i will send it to you ?

**Comment by bassemgithub** [comment]
i sended it by mail

**Comment by bassemgithub** [comment]
@bodymovin  i forget to say that i compiled it into windows is it ok ?

**Comment by bodymovin** [comment]
yes, should be fine

**Comment by bassemgithub** [comment]
@bodymovin  i shared the file by mail hope you can test it.
i would like to retry the creation
can you give me more detail how you create the zxp extension please ?
thanks in advance

**Comment by bassemgithub** [comment]
hi bodymovin, 
any news about this 
thanks

**Comment by bodymovin** [comment]
Hi, I sent you an email yesterday.
Let me know if you got it

**Comment by bassemgithub** [comment]
yes i got it i replyed you 
Thanks
