### ISSUE TITLE
Smooth Animations

### ISSUE THREAD

**Issue by peterlunglum** [bodymovin/bodymovin#400]
@bodymovin ,

I've been using the plugin to animate shape layers, creating paths and generating strokes and outputting those animated strokes (I'm using the start and end keyframes as well as color slider to change the lines colors as theyre animating in and out) into SVG. I've noticed though that the animation isn't as smooth and robust for these types of animations as their desktop counterparts. Is it better to animate shape layers as opposed to strokes generated by the effects panel in after effects? I'm just curious if you could explain what types of presets/libraries/effects in AE we should avoid if we want to make well performing animations. Thanks!

**Comment by bodymovin** [comment]
Hi, I'm not sure I understand which animations work better than others. 
When you say their desktop counterparts, what are you comparing them to?
Can you share an .aep with examples?

**Comment by themanisingh** [comment]
I'm using Plugin called Motion v2 by Mt. Mograph. and on export i can't see any effect i added using that plugin.
[Here](https://www.dropbox.com/s/bcktx9pihvtgpc8/Git%20hub%20share%20Wake%20up%20animation.aep?dl=0) is the dropbox link to .aep project file.

**Comment by bodymovin** [comment]
@themanisingh Hi, I think with the latest version, it should work fine.

**Comment by cmalven** [comment]
Using Motion 2 on a little demo project to test bodymovin. Noticing that the `Warp` effect (which automatically stretches/squashes to match movement) isn't appearing in the exported animation. Should it be, as far as you know? If so, is there anything special I need to change in my export settings to see this effect?

(BTW, I'm aware that this original issue is very poorly-named, vague and unhelpful in general, I'm only posting this here because it already mentions Motion v2).

**Comment by bodymovin** [comment]
@cmalven Hi, unfortunately, the warp effects is not supported by the plugin.

**Comment by cmalven** [comment]
Thanks @bodymovin your comment to @themanisingh above made me think that it might work.
