### ISSUE TITLE
How to set the text in AE with all the character set? 

### ISSUE THREAD

**Issue by Vinothapplife** [bodymovin/bodymovin#462]
Hi @bodymovin ,

Thanks for this plugin, very nice one!.

Dynamic text in animation:
I have few implementation with this , i am not able to pass dynamic text.  if try to change the text but its getting error.  Then i found this link https://github.com/bodymovin/bodymovin/issues/238 , its useful. 

Can you guide us How to set the text in AE with all the character set?  and how to export all character ?

Thanks,
Vinoth

**Comment by bodymovin** [comment]
I just add an extra text layer for each font I need with all the characters I want exported.
I suggest that you set the in point of those text layers to be off the animation segment so they never get really rendered.

**Comment by Vinothapplife** [comment]
@bodymovin Thanks for you reply ! if you don't mine can you send me the any samples .aep file.

**Comment by vdias38** [comment]
Hi @bodymovin, I have the same issue 'Missing character from exported characters list: Regular Arial' but I don't change text dynamically and select glyphs on export. So I don't understand why characters are missing.
I share [here](https://drive.google.com/file/d/1tfy1bWQo4dk_s4ZYPIcn7R18vWZRcYc2/view?usp=sharing) my .aep and [link to demo](https://dl.infomobi.app/2Y8muRV) where you'll find warnings on console logs.

Thanks for your help.

PS: I also have performance issues with this animation. I don't believe it's due to this warning, but I'll check with font on svg. If you see any issue on aep that can decrease performance please let me know.

**Comment by bodymovin** [comment]
@vdias38 Hi, the warning is because text gets edited product of being inside a fixed text box. I'll have it fixed for the next deploy, but you can ignore it.
Regarding performance you are using the fill effect that translates to an svg filter which might have a big impact on performance. I'd try removing those effects if possible.

**Comment by vdias38** [comment]
@bodymovin I've observed the logs have a significant impact on performance. 
I've uploaded on youtube a [screencast showing the drop on fps](https://www.youtube.com/watch?v=tOuYvFAAeqs) when lottie.js log on console: 
- On left corner of screen you can see fps provided by rendering of chrome dev tools
- On right corner of screen you can see the number of logs emitted.

You'll see the fps decreasing (approx. -60%) exactly when logs emitted number increase, between 5-6 sec.. And when lottie stop to log the fps rise back to 60fps.

**Comment by bodymovin** [comment]
logs have a higher impact on performance when the console is open, if it's closed it shouldn't affect.
Having said that, I'll deploy a new version this week so those logs go away.

**Comment by vdias38** [comment]
Great! thanks for your support

**Comment by vdias38** [comment]
Hi @bodymovin, I've found the reason of fps decrease. 
![Adobe_After_Effects_-__Users_victor_dias_Dow______Modern___Clean_After_Effects_Modern___Clean_Presentation__converted__aep__](https://user-images.githubusercontent.com/9011612/58380664-a66ff100-7fab-11e9-9a4a-3d4040d84088.png)

It occurs on scene 5 composition, and raise huge text warnings.  The source text was "instantiate" but not used, maybe a human mistake, without any visual effect, BUT seems to raise an "overload" on lottie-web. I've removed and it works fine.

I share the resolution because could help someone with similar issue, the console warnings were only the visible part of a deeper issue.

Thanks for your support.

**Comment by bodymovin** [comment]
@vdias38 thanks for lloking into it.
If you have an .aep with this reduced case it would be great.

**Comment by l00ney2** [comment]
> 

Hi from me. Could I have an example how to do this in AE too with any samples .aep file? Because it's not very clear how this is happening.
