### ISSUE TITLE
Extremely high CPU usage

### ISSUE THREAD

**Issue by jackmcdade** [bodymovin/bodymovin#487]
Hey there, I'm seeing a 130% CPU usage for my animation. The JSON file is 1mb, which i'm assuming has something to do with it. Do you have any recommendations for optimization?

**Comment by bodymovin** [comment]
Hi, can you share the .aep so I can take a look?

**Comment by jackmcdade** [comment]
Sure thing! Here's a download link: <http://d.pr/f/MGGx9>

**Comment by bodymovin** [comment]
Yes, there are a lot of paths in this animation. A quick count gave me 1938.
There is an issue converting AI layers to AE shapes.
AE adds an unnecessary square path and a merge path.
For example in your composition "square", on any of the layers (smoke_3/House in Mountains Outlines for example), inside Contents > inside "Group 1" and "Group 2" if you remove the inner Group 1 and the Merge Paths in the Contents, you'll be saving a lot of shapes.
Unfortunately, you need to go through each layer and remove them manually.
There is an additional issue in your case, because of the size of your Comp.
Since it measures 3200*2400, those square shapes are extremely large.
