### ISSUE TITLE
Bodymovin in Wordpress

### ISSUE THREAD

**Issue by staytoooned** [bodymovin/bodymovin#549]
I'm not able to render a bodymovin animation in my Elegant Themes Divi Theme site. It works as a blank HTML page, but will not work in Wordpress.

I'm referencing the javascript source files and div exactly like a blank html page along with the CSS. Nothing happens when the page loads. 

Please help!

**Comment by bodymovin** [comment]
Can you share a link where it fail so I can check it out?

**Comment by staytoooned** [comment]
I am not able to add the bodymovin to a Wordpress page directly. It can only work if I create a blank html page with the bodymovin and enter the URL using iframe on the Wordpress page. Any way bodymovin can work directly in Wordpress without using iframe?

Thanks.

Jane

**Comment by bodymovin** [comment]
Link with the issue?
as long as you can include js files to your wordpress, it should work.

**Comment by staytoooned** [comment]
Yes, I added the link to the js files and it didn’t work. It may have something to do with rendering SVG files in Wordpress. 
The only way to display the bodymovin is by using the iframe element and running it from a URL.

**Comment by DaanDirk** [comment]
I have bodymovin running on a couple of wordpress sites. So it can be done. :-)
Have you checked whether bodymovin.js and your script are really on the page and accessible when the page is loaded? If not fix that. Some browsers also want everything to be from the same domain.

You can add some code to your functions.php so you can put .js and .json files into the media library.
`/* add filetype json to media library */`
`function my_myme_types($mime_types){`
`    $mime_types['json'] = 'json'; //Adding json extension`
`    $mime_types['js'] = 'js'; //Adding js extension`
`    return $mime_types;`
`}`
`add_filter('upload_mimes', 'my_myme_types', 1, 1);`

Then make sure the js is below the bodymovin div like so:
`<div style="width:100%;float:left;" id="bodymovin"></div>`
`<script src=" /wp-content/uploads/bodymovin.js" type="text/javascript"></script>`
`<script src=" /wp-content/uploads/yourbodymovinscript.js" type="text/javascript"></script>`
Maybe you need to use a plugin like 'Raw HTML' to prevent wordpress from doing some automatic formatting you don't want to happen.

On top of that, in your script make sure the page is loaded before the you play the animation:
`anim.addEventListener("DOMLoaded", function() {`
`anim.play();`
`}`

Did you check whether the bodymovin div is visible, has width and height etc?
In most cases you will have to change/set the css for the bodymovin div.
Inspect the bodymovin div with your browser (right click: <inspect element> or something like that) and check whether you can see the svg that bodymovin loads onto the page.
If not, bodymovin isn't loading the animation properly.
If yes, you need to change the css in on your page to make sure the div and its content can be seen.

Good luck!

**Comment by staytoooned** [comment]
Thank you for all your help! I’ll let you know if this works.

**Comment by staytoooned** [comment]
I tried everything you suggested and nothing works. The only thing that works in Wordpress is if I put a basic html file in the same folder as the data.json file and use an iframe element sourcing the html url.
I’m using the DIVI theme from Elegant Themes.

**Comment by bodymovin** [comment]
Do you have a link with your wordpress site loading the bodymovin script that I can check?

**Comment by staytoooned** [comment]
I’m running bodymovin with the iframe on this page: http://www.maxitmedia.co <http://www.maxitmedia.co/>

Here’s a page where it’s not working:

http://www.maxitmedia.co/portfolio/ <http://www.maxitmedia.co/portfolio/>

**Comment by bodymovin** [comment]
It's looking for the data.json file in this location:
http://www.maxitmedia.co/portfolio/data.json
but it's returning an error.
can you make sure it's uploaded there or specify another route?

**Comment by staytoooned** [comment]
I tried specifying the route in the index.js file:

http://www.maxitmedia.co/scripts/maxit/devices/data <http://www.maxitmedia.co/scripts/maxit/devices/data.json>.json 

Please check it again. Thank you.

**Comment by bodymovin** [comment]
it seems to be working right?
I see a device animation as soon as I visit the portfolio page

**Comment by staytoooned** [comment]
I’ll try it in a different browser. It might be cached to the old one.

**Comment by staytoooned** [comment]
Looks like it’s working!

How can I specify a smaller height and width?

Thank you so much for your help!

**Comment by bodymovin** [comment]
the svg takes the space available from it's parent container.
You'll probably need to change the style applied to your div with id "bm"

**Comment by staytoooned** [comment]
Thanks!

**Comment by Digital-Harmony** [comment]
@staytoooned  How did you get this working with the Divi theme?  Could you please share the steps you took, as I am trying to do the exact same thing.  Thanks!!

**Comment by rezwanferdous** [comment]
I need help on this.i'm using the divi theme It preview the animation when i directly add the code to header.php but when i try to add on the page by 
<div id="bodymovin"></div>
it doesn't work. 
This is the link of my page-  https://integratedmobilemarketing.com/dev12/311-2/
it gives me these errors- 

> Uncaught TypeError: Cannot read property 'appendChild' of undefined
>     at SVGRenderer.configAnimation (bodymovin.js:5)
>     at AnimationItem.configAnimation (bodymovin.js:9)
>     at XMLHttpRequest.r.onreadystatechange (bodymovin.js:9) 

i added the necessary json and bodymovin.js file
```
path: 'https://integratedmobilemarketing.com/dev12/wp-content/uploads/2017/10/data.json'
<script src="https://integratedmobilemarketing.com/dev12/wp-content/uploads/2017/10/bodymovin.js" type="text/javascript"></script>
```

**Please help!!!**

**Comment by bodymovin** [comment]
It seems to be working.
Did you fix it?

**Comment by rezwanferdous** [comment]
yes, thanks a lot for the post @bodymovin  i pasted the script code in header.php like a stupid , lastly i just pasted them to footer.php and it worked... awesome..thanks a lot

**Comment by Ergoberg** [comment]
@DaanDirk @staytoooned @rezwanferdous If any of you would be able to share a more comprehensive guide on how you made it work with Wordpress I would be immensely grateful!

**Comment by tesla4** [comment]
Hello everybody

Since I had the same problem including Bodymovin files to Wordpress, I'd like to share make workaround. Expecially @DaanDirk 's post made everything work for me. After all it's ridiculously simple: 

I started with the exported "demo.html" file and its "data.json". Also I had two images in a folder called "images". 

1. Copy or directly edit the "demo.html" file. **Get rid of everything that is not Javascript**: Delete all html-tags including the whole style-Section, the \<div\>-entry and all closing tags. Also delete the <script> tags. Make sure to delete both </script> (At a first try I missed the one right after the first very long javascript part). 
2. Now you should have nothing but Javascript in your file. A first part with this confusing code block and a second part with the variables. Now **save it as a Javascript file** (e.g. "bodymovin.js"). 
3. Because Wordpress' pages are mainly blocks of PHP, references to subfolders, files etc. is not easily manageable by hand. This means, for the reference to our animation files, we we have to find a folder on Wordpress that doesn't change relating to the page-position. Therefore we can't load the files into the child theme folder. It's even simpler: We load it straight to wordpress by the media uploader. The media upload is blocked for *.js and *.json files but we can change that: 
`anim.addEventListener("DOMLoaded", function() {anim.play();}` 
**Just insert this code into the "functions.php"** of your child theme e.g. at the end of it. If you don't have a "functions.php" file in your child theme folder, you can just create one and fill it with this code. 
4. Now open the Wordpress surface and go to the media uploader. Make sure that **uploaded files won't get a permalink with a year or date**. The files need to be in the same folder "/wp-content/uploads/". If that's not the case, you can edit it under "settings > media" on Wordpress. 
5. We have to add a bit code to your Javascript file. Open it (e.g. "bodymovin.js") again and go to the part where it says `var params = { `. Before the closing brace **we add two new parameters**. `path `for the url to the *.json file and `assetsPath `for the images. The code should look similar to this: 
`var params = {`
       `     container: document.getElementById('lottie'),`
        `     renderer: 'svg',`
        `     loop: true,`
        `     autoplay: true,`
        **`     path: '/wp-content/uploads/data.json',`**
	**`     assetsPath: '/wp-content/uploads/`**
    `};`
6. Save your Javascript file and **upload it with the "data.json" file and all images to Wordpress** using the media uploader in the Wordpress surface. 
7. Now place your Bodymovin \<div\>-tag **`<div id = "lottie"></div>`** anywhere you want. I wanted to have it in the title segment of every page, so I wrote it into the "header.php" file in my child theme folder. Style it then with css (height, width, etc.). 
8. The last step is to reference to your uploaded Javascript file. I did this in the "footer.php" right above the closing body tag \</body\>. Add this line: 
	**`<script src="/wp-content/uploads/bodymovin.js" type="text/javascript"></script>`**

I hope this workaround is comprehensible and will save you from trying. 

BR Chris

**Comment by dolanb12** [comment]
After a day... still can't get this to work @tesla4 

Did everything I could. Any suggestions?

There should be a button animation showing at the bottom in the section with headline "We look forward to speaking with you."

http://qz1.d9c.myftpupload.com/

Thanks,

Brendan

**Comment by wedza** [comment]
Thanks for your comprehensive explaination @tesla4 . It has been very helpful for me (and hopefully other peoples).

I entoutered some weird issues (probably due to some WP limitations), and would like to share my workarounds to help next people who has them.

- If you want to **integrate multiple animations in one single page**, sometimes, the second animation will come after the first one. Even if you placed the div element well after (like [in this issue](https://github.com/airbnb/lottie-web/issues/106)).

In my case, changing only the div ID (in the .js file, after document.getElementById, and in the page) wasn't working for me, for some reason. I needed to **rename the js file like the div id for the animation to work** (like myid.js).


- I also found that **renaming the data.json was breaking my animation**, even If I pointed to the correct path in the .js file. So I created by FTP one folder by animation, where there are the .js file, and corresponding data.json.


- Lastly, do not forget to place the <script> line **after** the <div> elements (if not, your animation will not work).

Here's an image of what your page should look like when you applied all this, hope that will help ^^

![image](https://user-images.githubusercontent.com/20335741/51319009-2c0eed80-1a5c-11e9-9dd7-89502ea54810.png)

And again, thanks to tesla4 for his comprehensive tutorial, and to all devs behing Bodymovin and Lottie.
