### ISSUE TITLE
Masks not correctly exported

### ISSUE THREAD

**Issue by lfoscari** [bodymovin/bodymovin#634]
I'm trying to export a text animation in SVG, but the masks that create the inner parts of the letter are ignored. 

What I'd like to obtain
<img width="236" alt="schermata 2017-09-20 alle 17 08 11" src="https://user-images.githubusercontent.com/6044125/30651585-73a71ac2-9e26-11e7-8257-0a872e6c1365.png">

What I get
<img width="387" alt="schermata 2017-09-20 alle 17 08 37" src="https://user-images.githubusercontent.com/6044125/30651596-7da2e434-9e26-11e7-9d7b-7876588e4b32.png">

I tried to toggle all the possible settings in BodyMoving but nothing worked. I tried both in Safari and Chrome.

I'm running After Effects CC 2017.2

If you need the .aep just ask.

**Comment by bodymovin** [comment]
Can you share the .aep?
I'll take a look at it

**Comment by lfoscari** [comment]
[MT_Logo_AN.aep.zip](https://github.com/bodymovin/bodymovin/files/1324098/MT_Logo_AN.aep.zip)
The masks are exported, but are not visible (You can see them by imposing and opacity lower than 1)

**Comment by bodymovin** [comment]
Hi, difference masks don't work well with the svg renderer.
Can you use the canvas renderer instead?

**Comment by lfoscari** [comment]
Thank you! That worked!

**Comment by pedrosantosux** [comment]
Hi, I'm stuggling with the exact same problem,
My animations are made out of masks that create inner paths (just like in the example above).
These inner paths get ignored and I can't figure out how to fix this in order to export my animations as SVG.

<img width="533" alt="bildschirmfoto 2017-11-15 um 13 55 32" src="https://user-images.githubusercontent.com/33528408/32837209-e9244858-ca0c-11e7-9d5e-2a1d0aa66ff7.png">
Ths is how it should look like

<img width="874" alt="bildschirmfoto 2017-11-15 um 13 56 40" src="https://user-images.githubusercontent.com/33528408/32837213-ecdc39ec-ca0c-11e7-8612-75f0347542d6.png">
here's how it looks after being exported

I apologize for the question but: what is the "canvas renderer" and how can I activate it? (I'm a designer so I don't have and coding knowledge)

**Comment by lfoscari** [comment]
Hi,
to activate other renderers than SVG you have to change the declaration in Javascript:

bodymovin.loadAnimation({
  container: element, // the dom element that will contain the animation
  renderer: 'svg’, <<< CHANGE
  loop: true,
  autoplay: true,
  path: 'data.json' // the path to the animation json
});

Change the “renderer” attribute into “canvas” or “html”. By doing so my masks rendered in the right way.

bodymovin.loadAnimation({
  container: element, // the dom element that will contain the animation
  renderer: ‘canvas',
  loop: true,
  autoplay: true,
  path: 'data.json' // the path to the animation json
});

The only issue with the canvas renderer is that you can’t use the slim version of the library, you HAVE to use the standard one and on a website is quite heavy.

**Comment by pedrosantosux** [comment]
Hi Luigi,

Thanx for your help, I ended up solving the problem by changing the type of masks in my animations (using only "ADDING" types of masks) and so I managed to export the animations correctly and then integrate them into my website by linking them to the json file and the player.

Cheers
Pedro

**Comment by bodymovin** [comment]
@karan-oneclick can you share the .aep project?

**Comment by karan-oneclick** [comment]
Sure.

[Loader.aep.zip](https://github.com/airbnb/lottie-web/files/1966734/Loader.aep.zip)

**Comment by karan-oneclick** [comment]
And the other thing, I saw in the upper comments about the sag renderer and canvas renderer. What is that and how can that is been used in the bodymovin?

**Comment by bodymovin** [comment]
@karan-oneclick unfortunately merge paths are not supported by the web player.
But if you remove from Layer `s > Contents > Group 1 > Path 1` I think it will work fine

**Comment by karan-oneclick** [comment]
Ohk, I'll try. Thanks for the help.

**Comment by BlueBunnyNation** [comment]
[SummerGrove.zip](https://github.com/airbnb/lottie-web/files/2774959/SummerGrove.zip)
I am having a blank screen when I render the project and run it in the browser using CodeKit. 
TypeX - Text Animation Tool | Magical Particles Pack: Handwritten Calligraphy Titles. 

This file is using Trapcode Particulate and TypeX - Text Animation Tool | Magical Particles Pack: Handwritten Calligraphy Titles from Envato.

**Comment by BlueBunnyNation** [comment]
I am having a blank screen when I render the project and run it in the browser using CodeKit. 

This file is using Trapcode Particulate and TypeX - Text Animation Tool | Magical Particles Pack: Handwritten Calligraphy Titles from Envato.

[SummerGrove.zip](https://github.com/airbnb/lottie-web/files/2774974/SummerGrove.zip)

**Comment by Linyan-ma** [comment]
@bodymovin my problems is when i use svg renderer,it works.when i change to canvas,it render a wrong animation. here is my json file:
about:blank#blocked

**Comment by trendsttler** [comment]
I created a mask with after effect 2019. in demo html file it works properly but we try this in react.native its not working there.

**Comment by bodymovin** [comment]
@trendsttler hi, what type of mask?

**Comment by dada78** [comment]
Hi bodymovin, our AE animation uses 3D cameras, as well as alpha and alphaInverted TrktMat settings. When exporting the preview looks bad as the masks are not being exported properly. I tried to follow the previous poster's example and changed the renderer to 'canvas' instead of html in addition to using  the canvas CDN: https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.5.3/lottie_canvas.min.js, however that brought up the fact that I am using a 3D camera in the AE comp, which pretty much prompts me to use the html renderer in the console. 

Question, is there a way for the masks to be exported correctly using the html renderer? Thanks!

**Comment by bodymovin** [comment]
@dada78 hi, unfortunately track matte masks are not supported on 3d layers. They are partially supported on the html renderer if they are in inner comps that don't have 3d applied to them.

**Comment by dada78** [comment]
Thanks @bodymovin ! Does the plugin support 3D layers and 3D camera? Thanks!

**Comment by bodymovin** [comment]
@dada78 it has partial support. Only a camera in the main comp, and not all properties are supported.
3d layers are partially supported as well.

**Comment by rohitmalakar** [comment]
Will the "set matte" effect  work for masking?

**Comment by buffetdzn** [comment]
I'm having the same problem, I don't know what's wrong with it, could you help? @bodymovin

**Comment by ozgurdevran** [comment]
Greetings to everyone. I am having exactly the same problem. Some of the masks I output json file are not visible. I am attaching my ae file. I'm waiting for your help
[dimmer.zip](https://github.com/airbnb/lottie-web/files/12345038/dimmer.zip)

**Comment by mehdimihanzadeh** [comment]
Watch this, your solution here 
https://youtu.be/55bNoZeugxE?si=w0uMh32JP89WB0WI
