### ISSUE TITLE
exporting SVG images

### ISSUE THREAD

**Issue by juancabrera** [bodymovin/bodymovin#86]
I'm using it and it works great. Thanks for building this!

Only thing is that the export always export assets to PNG, is there anyway that it export the assets to actual SVG ? all of the assets are vectorial (Illustrator)

**Comment by bodymovin** [comment]
you should convert your layers of illustrator on .ae to shapes.
right click on them and select: Create shapes from Vector Layer.
there are some issues with merge paths but usually it works fine.

**Comment by juancabrera** [comment]
That did it!
Thank you so much!

**Comment by Shirkit** [comment]
Hello,

I'm also having issues while exporting my animation. It exports everything as PNG instead of SVG, I tried to convert to Shape layers, but it breaks my animation, leaving some of them just outlined and not filled, the corners stays a bit transparent. If that wasn't enough, it's still exporting as PNGs.

I saved each layer as SVG on Illustrator and changed the data.json to use the new path img_0.svg, but it won't work, it still tries to load the png.

**Comment by flickitty** [comment]
I'm having problems with Illustrator Layers as well. The vector shape is extremely simple, a white stroke with a solid red fill. I use "Create Shapes From Vector Layers", and everything looks fine in After Effects. When I render with bodymovin, the shape is exported but exerything is opposite- what was alpha is now solid and the solids are alpha.

**Comment by honeyhorny** [comment]
i'm having problem same @flickitty 
![screen shot 2560-05-30 at 4 55 27 pm](https://cloud.githubusercontent.com/assets/12539087/26578385/dff137e2-4559-11e7-9713-d09c191200fa.png)
![screen shot 2560-05-30 at 4 56 27 pm](https://cloud.githubusercontent.com/assets/12539087/26578386/dff21fd6-4559-11e7-885d-f6eb68db58d8.png)

**Comment by coryarmbrecht** [comment]
@flickitty @honeyhorny My issue was the same (seeming) as yours. My shape also had some compound and merge paths. I tried exporting my .ai files to older versions of Illustrator; as either Illustrator 8 or CC, and that worked.
